import { Theme, Container } from '@radix-ui/themes'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import SiteFooter from './components/SiteFooter'
import SiteHeader from './components/SiteHeader'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Shagi Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Theme appearance="light" accentColor="violet" grayColor="slate" panelBackground="solid" radius="large">
          <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
            <SiteHeader />
            <main style={{ flex: 1 }}>
              <Container size="4" p="4">
                {children}
              </Container>
            </main>
            <SiteFooter />
          </div>
        </Theme>
      </body>
    </html>
  )
}
